package com.yondervision.mi.dao.impl;

import java.util.HashMap;
import java.util.List;

import com.yondervision.mi.dao.CMi711DAO;
import com.yondervision.mi.dto.Mi711Example;

public class CMi711DAOImpl extends Mi711DAOImpl implements CMi711DAO {

    
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table MI711
     *
     * @abatorgenerated Mon Sep 25 09:46:34 CST 2017
     */
    public List<HashMap<String,Object>> selectGroupMi711(Mi711Example example) {
        List<HashMap<String,Object>> list = (List<HashMap<String,Object>>)getSqlMapClientTemplate().queryForList("CMI711.abatorgenerated_selectGroupMi711", example);
        return list;
    }

 
}